### ISSUE TITLE
Bug: wget and sudo

### ISSUE THREAD

**Issue by 0n1cOn3** [namukcom/SynologyCloudFlareDDNS#2]

**Comment by 0n1cOn3** [comment]
Hi namukcom

iv tried to install your Cloudflare "Plugin". But im stuck on two problems:

- wget is outdated on DSM
- Sudo does not work: No Permission

Im running DSM 6.2.2-24922 Update 4
DSM 218+
With ipkg installed ; No Update available here for wget too.

DSM 6.2.2-24922 Update 4

**Comment by namukcom** [comment]
1. The account you try to "sudo" should be a memeber of "administrators".
 - Control Panel - Groups - administrators - Edit Members - add your account.

2. You can user "curl" instead,
 But wget still works.

**Comment by namukcom** [comment]
I modified the .md file to use "curl". Thanks.
