### ISSUE TITLE
Grey Cloud (bypass) on cloudflare after update

### ISSUE THREAD

**Issue by planetahuevo** [namukcom/SynologyCloudFlareDDNS#3]
Hi, thanks for the code. It works. 
I have an issue, everytime I update the IP, the cloudflare is setup to bypass , using the grey cloud. 
I am using cloudflare for the extra features, so, would be possible to let the bypass as it was?

If it is grey leave it grey and the other way around.

Thanks

**Comment by namukcom** [comment]
hi.
I don't remeber why I wrote this code,
~~just delete line #112 ('proxied'=>false).
It's optional.~~

I'll test and update soon.

-----------------------
Update Feb 10, 2020
I updated the source not to change proxy setting.
Just download again and try it!

Thanks.

**Comment by planetahuevo** [comment]
Thank you! 
Found it on the code too. It works :)
