### ISSUE TITLE
Setup Proxy status as "Proxied" as default

### ISSUE THREAD

**Issue by Vinery** [namukcom/SynologyCloudFlareDDNS#4]
Appreciate your code, for protect the real IP, it should be "Proxied" as default better than "DNS only".

**Comment by namukcom** [comment]
"SynologyCloudFlareDDNS" Script doesn't change "Proxied" setting.

So it remains as you set.
(If you manually set it as proxied, it remains proxied. If you don't it doesn't.)

**Comment by Vinery** [comment]
I add the ` 'proxied'=>true`  after line 112 solved the issue, maybe the defalult vlaue is "false" when ignore the `proxied`  parameter.

https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

**Comment by namukcom** [comment]
If you run a just website, "Proxied" option should be set true.
But if you connect DDNS to "ssh, rdp, etc..."
"Proxied" option should be set false.

So the script should not change the "proxied" option.
If you need to change the proxied option, change in the dashboard in CF.
This script will not.
