### ISSUE TITLE
How about guiding a triggered task method?

### ISSUE THREAD

**Issue by y-kim** [namukcom/SynologyCloudFlareDDNS#7]
Hi! Thank you for the code. It's very useful.

By the way, how about guiding a triggered task method instead of SSH.

It's more easy to novice and it can also guarantee continuous reflections after DSM updates.
Or we need to modify ddns_provider.conf whenever the updates override it.

In my case, I created a triggered task as boot-up event for root user.
Run command section is very simple:
`curl https://raw.githubusercontent.com/namukcom/SynologyCloudflareDDNS/master/setddns.py | python3 -`

We need onetime "run" after creation of the task, not to wait until next boot-up.

**Comment by namukcom** [comment]
README.md has been updated thanks to you.
